# Generated by Django 5.2 on 2025-05-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permissao',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('funcionario', 'Funcionário'), ('estudante', 'Estudante')], default='estudante', max_length=20),
        ),
    ]
