# Generated by Django 5.2 on 2025-05-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0001_initial'),
        ('core', '0001_initial'),
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatura',
            options={'permissions': [('view_outras_candidaturas', 'Can view candidaturas of other students')]},
        ),
        migrations.RenameField(
            model_name='candidatura',
            old_name='CNIouPassaporteEntregue',
            new_name='cni_ou_passaporte_entregue',
        ),
        migrations.RenameField(
            model_name='candidatura',
            old_name='DataSubmissao',
            new_name='data_submissao',
        ),
        migrations.RenameField(
            model_name='candidatura',
            old_name='DeclaracaoMatriculaEntregue',
            new_name='declaracao_matricula_entregue',
        ),
        migrations.RenameField(
            model_name='candidatura',
            old_name='DeclaracaoRendimentoEntregue',
            new_name='declaracao_rendimento_entregue',
        ),
        migrations.RenameField(
            model_name='candidatura',
            old_name='DeclaracaoResidenciaEntregue',
            new_name='declaracao_residencia_entregue',
        ),
        migrations.RenameField(
            model_name='candidatura',
            old_name='DeclaracaoSubsistenciaEntregue',
            new_name='declaracao_subsistencia_entregue',
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='estudantes.estudante'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='core.residencia'),
        ),
    ]
