# Generated by Django 5.2 on 2025-04-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('em_analise', 'Em Análise')], default='pendente', max_length=20, verbose_name='Estado da Candidatura'),
        ),
    ]
