# Generated by Django 5.2 on 2025-04-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('outros', 'Outros')], default='residencial', max_length=50),
        ),
    ]
