# Generated by Django 5.2 on 2025-05-18 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='cama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes', to='core.cama'),
        ),
        migrations.AlterField(
            model_name='cama',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camas', to='core.quarto'),
        ),
        migrations.AlterField(
            model_name='cama',
            name='residente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camas', to='core.residente'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='core.edificio'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencias', to='core.edificio'),
        ),
    ]
