# Generated by Django 5.2 on 2025-04-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_edificio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Individual'), ('duplo', 'Duplo'), ('triplo', 'Triplo')], default='individual', max_length=20),
        ),
    ]
